### PR TITLE
Bringing build system up to date

### PR DESCRIPTION
**Pull request by alexgorbatchev**
This is a pretty big PR, it has the following general changes (Issue #6):

* Replaces `Makefile` with `gulp`
* Removes `jsdoc` for not being used that much
* Setups up Karma for continuos testing/development
* Renamed `src` to `lib`
* `gulp build` compiles to `lib` and `dist`
* `gulp gh-pages` published to `gh-pages` branch

cc @eventualbuddha @iamJoeTaylor @TRMW

### CODE REVIEW

**Comment by iamJoeTaylor** [comment]
I'm fine with that. We can just publish the binary in Releases. Can we make an issue to do CDN.

**Comment by alexgorbatchev** [comment]
#16 - done

**Comment by iamJoeTaylor** [comment]
I think I only have one outstanding comment on this: "It seems weird we have the UMD style in index and a dist file. Something seems off to me."

**Comment by alexgorbatchev** [comment]
fixed

**Comment by iamJoeTaylor** [comment]
+1

**Pull request merged**
